version: '3'

services:
    web:
        build: web
        image: cricco95/exploitable_web
        ports:
            - "80:80"
        volumes:
            - "/mnt/hgfs/Shared_Folder/exploitable/web:/var/www/html"            
        links:
            - db
    db:
        build: db
        image: cricco95/exploitable_db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=exploitable
    phpmyadmin:
        build: phpmyadmin
        image: cricco95/exploitable_phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db
    ubuntu:
        build: ubuntu
        image: cricco95/exploitable_ubuntu
        ports:
            - "2222:22"
